name: jsbundle Build and Upload 

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: use Node.js 13.2.0
        uses: actions/setup-node@v1
        with:
          node-version: 13.2.0

      - name: setup kernel for react native, increase watchers
        run: echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p

      - name: npm install
        run: npm install 
        shell: bash
    
      - name: build jsbundle 
        run: |
          npm run build:ios
          npm run build:android
        shell: bash

      - name: upload jsbundle
        uses: actions/upload-artifact@v2
        with:
          name: jsbundle-${{ github.event.pull_request.number }}
          path: jsbundle

      - name: comment about jsbundle 
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            jsbundle is built and uploaded
            
            What to do next:
            - [ ] reload the new jsbundle
            - [ ] tophat the new App
          reactions: '+1'


