name: jsbundle Build and Upload 

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
   
      - name: use Node.js 13.2.0
        uses: actions/setup-node@v1
        with:
          node-version: 13.2.0

      - name: npm install
        run: npm install 
        shell: bash
    
      - name: run test
        run: npm run test
        shell: bash
        
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: use Node.js 13.2.0
        uses: actions/setup-node@v1
        with:
          node-version: 13.2.0

      - name: npm install
        run: npm install 
        shell: bash
    
      - name: build jsbundle 
        run: |
          npm run build:ios
          npm run build:android
        shell: bash

      - name: upload and generate QR code
        uses: ottocho/gzcz@master
        with:
          dist_path: 'jsbundle'
          app_name: 'szzz'
          storage_project_id: ${{ secrets.GCP_PROJECT_ID }}
          storage_bucket: ${{ secrets.GCP_BUCKET_NAME }}
          storage_auth_token: ${{ secrets.GCP_AUTH_TOKEN }}
