name: testing gzcz

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
      - uses: ottocho/gzcz@master
        with:
          setup_command: npm install
          build_command: npm run build
          dist_path: 'dist'
          app_name: 'szzz'
          storage_type: 'gcs'
          token: ${{ secrets.GITHUB_TOKEN }}
